kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: demo-service
  labels:
    app: demo-service
    app.kubernetes.io/component: demo-service
    app.kubernetes.io/instance: demo-service
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/part-of: demo-service-app
spec:
  to:
    kind: Service
    name: demo-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
